#!/bin/bash

# validate_frontmatter.sh - Validate frontmatter compliance in thought documents
#
# Usage:
#   ./hack/validate_frontmatter.sh [file_path]
#   ./hack/validate_frontmatter.sh --all
#
# Exit codes:
#   0 - All validations passed
#   1 - Validation failures found
#   2 - Script error (invalid usage, file not found, etc.)

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_success() { echo -e "${GREEN}✓${NC} $1"; }
print_error() { echo -e "${RED}✗${NC} $1"; }
print_warning() { echo -e "${YELLOW}⚠${NC} $1"; }
print_info() { echo -e "${BLUE}ℹ${NC} $1"; }

# Validate single file
validate_file() {
    local file=$1
    local failures=0

    print_info "Validating: $file"

    # Check file exists
    if [ ! -f "$file" ]; then
        print_error "File not found: $file"
        return 2
    fi

    # Extract frontmatter (lines between first two ---)
    if ! grep -q "^---$" "$file"; then
        print_error "No frontmatter found (missing --- markers)"
        return 1
    fi

    local frontmatter=$(awk '/^---$/{flag++; next} flag==1' "$file")

    # Check for _generated: true field
    if ! echo "$frontmatter" | grep -q "^_generated: true"; then
        print_error "Missing '_generated: true' field (manual frontmatter detected)"
        print_warning "This frontmatter was manually constructed instead of using hack/generate_frontmatter.sh"
        ((failures++))
    else
        print_success "Frontmatter generated by script"
    fi

    # Check for valid YAML syntax (basic check)
    if ! echo "---"; echo "$frontmatter"; echo "---" | python3 -c "import sys, yaml; yaml.safe_load(sys.stdin)" 2>/dev/null; then
        print_error "Invalid YAML syntax in frontmatter"
        ((failures++))
    else
        print_success "Valid YAML syntax"
    fi

    # Check required fields based on doc_type
    local doc_type=$(echo "$frontmatter" | grep "^doc_type:" | sed 's/doc_type: //' | xargs)

    if [ -z "$doc_type" ]; then
        print_error "Missing required field: doc_type"
        ((failures++))
    else
        print_success "doc_type: $doc_type"

        # Type-specific validation
        case $doc_type in
            research)
                # Optional fields, just note if missing
                ;;
            plan)
                # Optional fields
                ;;
            implementation)
                if ! echo "$frontmatter" | grep -q "^plan_reference:"; then
                    print_warning "Missing recommended field: plan_reference"
                fi
                ;;
            review)
                if ! echo "$frontmatter" | grep -q "^review_status:"; then
                    print_error "Missing required field: review_status"
                    ((failures++))
                fi
                if ! echo "$frontmatter" | grep -q "^reviewer:"; then
                    print_error "Missing required field: reviewer"
                    ((failures++))
                fi
                ;;
            learning)
                if ! echo "$frontmatter" | grep -q "^learning_type:"; then
                    print_error "Missing required field: learning_type"
                    ((failures++))
                fi
                ;;
            *)
                print_warning "Unknown doc_type: $doc_type"
                ;;
        esac
    fi

    # Check filename convention: YYYY-MM-DD-[optional-ticket]-description.md
    local filename=$(basename "$file")
    if ! echo "$filename" | grep -qE '^[0-9]{4}-[0-9]{2}-[0-9]{2}-.*\.md$'; then
        print_warning "Filename doesn't follow convention: YYYY-MM-DD-[ticket]-description.md"
        print_info "Actual: $filename"
    else
        print_success "Filename follows convention"
    fi

    # Summary
    echo ""
    if [ $failures -eq 0 ]; then
        print_success "All validations passed for $file"
        return 0
    else
        print_error "$failures validation failure(s) found in $file"
        return 1
    fi
}

# Main logic
if [ $# -eq 0 ]; then
    echo "Usage: $0 <file_path> | --all"
    echo ""
    echo "Validate frontmatter compliance in thought documents"
    echo ""
    echo "Options:"
    echo "  <file_path>    Validate a specific file"
    echo "  --all          Validate all documents in thoughts/"
    exit 2
fi

if [ "$1" == "--all" ]; then
    print_info "Validating all documents in thoughts/"
    echo ""

    total=0
    passed=0
    failed=0

    for file in thoughts/**/*.md; do
        if [ -f "$file" ]; then
            ((total++))
            if validate_file "$file"; then
                ((passed++))
            else
                ((failed++))
            fi
            echo ""
        fi
    done

    echo "================================"
    echo "Summary:"
    echo "  Total: $total"
    echo "  Passed: $passed"
    echo "  Failed: $failed"
    echo "================================"

    [ $failed -eq 0 ] && exit 0 || exit 1
else
    validate_file "$1"
fi
